import { Project } from "@/types/common";

// ---- MOCK DATA ----
export const mockProjectWebsite: Project = {
  id: "board-1",
  title: "Dự án Ecommerce Website",
  description: "Quản lý công việc phát triển website bán hàng",
  columnOrderIds: ["col-1", "col-2", "col-3", "col-4"],
  users: [
    {
      id: "u1",
      email: "duy@example.com",
      displayName: "Khánh Duy",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    {
      id: "u2",
      email: "linh@example.com",
      displayName: "Minh Linh",
      avatar: "https://i.pravatar.cc/150?img=2",
    },
    {
      id: "u3",
      email: "hieu@example.com",
      displayName: "Trung Hiếu",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
    {
      id: "u4",
      email: "thao@example.com",
      displayName: "Ngọc Thảo",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
  ],
  columns: [
    {
      id: "col-1",
      projectId: "board-1",
      title: "Backlog",
      cardOrderIds: ["card-1", "card-2"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-1",
          projectId: "board-1",
          columnId: "col-1",
          title: "Phân tích yêu cầu khách hàng",
          description: "Thu thập yêu cầu từ khách hàng và viết tài liệu SRS.",
          cover:
            "https://images.unsplash.com/photo-1758243488339-10c80d530943?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
          comments: [
            {
              id: 1,
              userId: "u1",
              userEmail: "duy@example.com",
              userAvatar: "https://i.pravatar.cc/150?img=1",
              userDisplayName: "Khánh Duy",
              content: "Mình đã tạo draft tài liệu SRS rồi nhé.",
              commentAt: new Date().toISOString(),
            },
          ],
          checklist: [
            { id: "chk-1", content: "Thu thập yêu cầu", completed: true },
            {
              id: "chk-2",
              content: "Xác nhận với khách hàng",
              completed: false,
            },
          ],
          memberIds: ["u1", "u2"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 7 * 86400000).toISOString(),
          _destroy: false,
        },
        {
          id: "card-2",
          projectId: "board-1",
          columnId: "col-1",
          title: "Thiết kế UI/UX",
          description: "Dùng Figma để thiết kế wireframe và prototype.",
          cover:
            "https://images.unsplash.com/photo-1758243488339-10c80d530943?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
          comments: [],
          checklist: [],
          memberIds: ["u3"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 14 * 86400000).toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-2",
      projectId: "board-1",
      title: "In Progress",
      cardOrderIds: ["card-3"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-3",
          projectId: "board-1",
          columnId: "col-2",
          title: "Phát triển trang chủ",
          description: "Code trang chủ bằng Next.js 15 + TailwindCSS v4.",
          comments: [
            {
              id: 2,
              userId: "u3",
              userEmail: "hieu@example.com",
              userAvatar: "https://i.pravatar.cc/150?img=3",
              userDisplayName: "Trung Hiếu",
              content: "Đã responsive xong phần header.",
              commentAt: new Date().toISOString(),
            },
          ],
          checklist: [
            { id: "chk-3", content: "Header + Navigation", completed: true },
            { id: "chk-4", content: "Hero section", completed: false },
          ],
          memberIds: ["u3", "u4"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-3",
      projectId: "board-1",
      title: "Review",
      cardOrderIds: ["card-4"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-4",
          projectId: "board-1",
          columnId: "col-3",
          title: "Kiểm thử chức năng giỏ hàng",
          description: "Viết test case và test API add/remove cart.",
          comments: [],
          checklist: [
            { id: "chk-5", content: "Test thêm sản phẩm", completed: true },
            { id: "chk-6", content: "Test xoá sản phẩm", completed: true },
            { id: "chk-7", content: "Test update số lượng", completed: false },
          ],
          memberIds: ["u2"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-4",
      projectId: "board-1",
      title: "Done",
      cardOrderIds: ["card-5"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-5",
          projectId: "board-1",
          columnId: "col-4",
          title: "Triển khai staging server",
          description: "Deploy bản thử nghiệm lên Vercel để khách hàng review.",
          comments: [],
          checklist: [],
          memberIds: ["u1", "u4"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 2 * 86400000).toISOString(),
          _destroy: false,
        },
      ],
    },
  ],
};

// ---- MOCK Project: MOBILE APP ----
export const mockProjectMobileApp: Project = {
  id: "board-2",
  title: "Dự án Mobile App",
  description: "Quản lý công việc phát triển ứng dụng di động",
  columnOrderIds: ["col-5", "col-6", "col-7", "col-8"],
  users: [
    {
      id: "u5",
      email: "an@example.com",
      displayName: "Quốc An",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    {
      id: "u6",
      email: "hoa@example.com",
      displayName: "Bảo Hoa",
      avatar: "https://i.pravatar.cc/150?img=6",
    },
    {
      id: "u7",
      email: "son@example.com",
      displayName: "Văn Sơn",
      avatar: "https://i.pravatar.cc/150?img=7",
    },
    {
      id: "u8",
      email: "mai@example.com",
      displayName: "Hồng Mai",
      avatar: "https://i.pravatar.cc/150?img=8",
    },
  ],
  columns: [
    {
      id: "col-5",
      projectId: "board-2",
      title: "Backlog",
      cardOrderIds: ["card-6", "card-7"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-6",
          projectId: "board-2",
          columnId: "col-5",
          title: "Phân tích tính năng ứng dụng",
          description: "Thu thập yêu cầu và xác định tính năng chính cho app.",
          cover:
            "https://images.unsplash.com/photo-1758243488339-10c80d530943?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
          comments: [
            {
              id: 3,
              userId: "u5",
              userEmail: "an@example.com",
              userAvatar: "https://i.pravatar.cc/150?img=5",
              userDisplayName: "Quốc An",
              content: "Đã tổng hợp xong danh sách tính năng.",
              commentAt: new Date().toISOString(),
            },
          ],
          checklist: [
            { id: "chk-8", content: "Thu thập yêu cầu", completed: true },
            {
              id: "chk-9",
              content: "Xác nhận với khách hàng",
              completed: false,
            },
          ],
          memberIds: ["u5", "u6"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 5 * 86400000).toISOString(),
          _destroy: false,
        },
        {
          id: "card-7",
          projectId: "board-2",
          columnId: "col-5",
          title: "Thiết kế giao diện mobile",
          description: "Thiết kế UI/UX cho app bằng Figma.",
          cover:
            "https://images.unsplash.com/photo-1758243488339-10c80d530943?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
          comments: [],
          checklist: [],
          memberIds: ["u7"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 10 * 86400000).toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-6",
      projectId: "board-2",
      title: "In Progress",
      cardOrderIds: ["card-8"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-8",
          projectId: "board-2",
          columnId: "col-6",
          title: "Lập trình màn hình đăng nhập",
          description: "Xây dựng màn hình login bằng React Native.",
          comments: [
            {
              id: 4,
              userId: "u7",
              userEmail: "son@example.com",
              userAvatar: "https://i.pravatar.cc/150?img=7",
              userDisplayName: "Văn Sơn",
              content: "Đã hoàn thành chức năng xác thực.",
              commentAt: new Date().toISOString(),
            },
          ],
          checklist: [
            { id: "chk-10", content: "UI đăng nhập", completed: true },
            { id: "chk-11", content: "Tích hợp API", completed: false },
          ],
          memberIds: ["u7", "u8"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-7",
      projectId: "board-2",
      title: "Review",
      cardOrderIds: ["card-9"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-9",
          projectId: "board-2",
          columnId: "col-7",
          title: "Kiểm thử chức năng đăng ký",
          description: "Viết test case cho màn hình đăng ký.",
          comments: [],
          checklist: [
            { id: "chk-12", content: "Test nhập thông tin", completed: true },
            { id: "chk-13", content: "Test xác thực email", completed: false },
          ],
          memberIds: ["u6"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-8",
      projectId: "board-2",
      title: "Done",
      cardOrderIds: ["card-10"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-10",
          projectId: "board-2",
          columnId: "col-8",
          title: "Triển khai bản beta lên TestFlight",
          description: "Đưa app lên TestFlight cho khách hàng thử nghiệm.",
          comments: [],
          checklist: [],
          memberIds: ["u5", "u8"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 3 * 86400000).toISOString(),
          _destroy: false,
        },
      ],
    },
  ],
};

// ---- MOCK PROJECT: SEO ----
export const mockProjectSEO: Project = {
  id: "board-3",
  title: "Dự án SEO Website",
  description: "Quản lý công việc tối ưu hóa SEO cho website",
  columnOrderIds: ["col-9", "col-10", "col-11", "col-12"],
  users: [
    {
      id: "u9",
      email: "phuc@example.com",
      displayName: "Minh Phúc",
      avatar: "https://i.pravatar.cc/150?img=9",
    },
    {
      id: "u10",
      email: "trang@example.com",
      displayName: "Thu Trang",
      avatar: "https://i.pravatar.cc/150?img=10",
    },
    {
      id: "u11",
      email: "khanh@example.com",
      displayName: "Bảo Khánh",
      avatar: "https://i.pravatar.cc/150?img=11",
    },
    {
      id: "u12",
      email: "tuan@example.com",
      displayName: "Anh Tuấn",
      avatar: "https://i.pravatar.cc/150?img=12",
    },
  ],
  columns: [
    {
      id: "col-9",
      projectId: "board-3",
      title: "Backlog",
      cardOrderIds: ["card-11", "card-12"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-11",
          projectId: "board-3",
          columnId: "col-9",
          title: "Phân tích từ khoá",
          description: "Nghiên cứu và chọn bộ từ khoá mục tiêu.",
          cover:
            "https://images.unsplash.com/photo-1758243488339-10c80d530943?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
          comments: [
            {
              id: 5,
              userId: "u9",
              userEmail: "phuc@example.com",
              userAvatar: "https://i.pravatar.cc/150?img=9",
              userDisplayName: "Minh Phúc",
              content: "Đã hoàn thành phân tích từ khoá cạnh tranh.",
              commentAt: new Date().toISOString(),
            },
          ],
          checklist: [
            { id: "chk-14", content: "Nghiên cứu từ khoá", completed: true },
            { id: "chk-15", content: "Chọn từ khoá chính", completed: false },
          ],
          memberIds: ["u9", "u10"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 6 * 86400000).toISOString(),
          _destroy: false,
        },
        {
          id: "card-12",
          projectId: "board-3",
          columnId: "col-9",
          title: "Tối ưu nội dung website",
          description: "Viết lại nội dung chuẩn SEO cho các trang chính.",
          cover:
            "https://images.unsplash.com/photo-1758243488339-10c80d530943?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
          comments: [],
          checklist: [],
          memberIds: ["u11"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 12 * 86400000).toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-10",
      projectId: "board-3",
      title: "In Progress",
      cardOrderIds: ["card-13"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-13",
          projectId: "board-3",
          columnId: "col-10",
          title: "Xây dựng backlink",
          description: "Tạo liên kết chất lượng cho website.",
          comments: [
            {
              id: 6,
              userId: "u11",
              userEmail: "khanh@example.com",
              userAvatar: "https://i.pravatar.cc/150?img=11",
              userDisplayName: "Bảo Khánh",
              content: "Đã liên hệ xong các đối tác.",
              commentAt: new Date().toISOString(),
            },
          ],
          checklist: [
            { id: "chk-16", content: "Danh sách website", completed: true },
            { id: "chk-17", content: "Gửi yêu cầu liên kết", completed: false },
          ],
          memberIds: ["u11", "u12"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-11",
      projectId: "board-3",
      title: "Review",
      cardOrderIds: ["card-14"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-14",
          projectId: "board-3",
          columnId: "col-11",
          title: "Kiểm tra tốc độ website",
          description: "Đánh giá và tối ưu tốc độ tải trang.",
          comments: [],
          checklist: [
            { id: "chk-18", content: "Kiểm tra PageSpeed", completed: true },
            { id: "chk-19", content: "Tối ưu hình ảnh", completed: false },
          ],
          memberIds: ["u10"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          _destroy: false,
        },
      ],
    },
    {
      id: "col-12",
      projectId: "board-3",
      title: "Done",
      cardOrderIds: ["card-15"],
      updatedAt: new Date().toISOString(),
      _destroy: false,
      cards: [
        {
          id: "card-15",
          projectId: "board-3",
          columnId: "col-12",
          title: "Báo cáo kết quả SEO",
          description: "Tổng hợp và gửi báo cáo cho khách hàng.",
          comments: [],
          checklist: [],
          memberIds: ["u9", "u12"],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deadlineDate: new Date(Date.now() + 4 * 86400000).toISOString(),
          _destroy: false,
        },
      ],
    },
  ],
};

export const mockProjects: Project[] = [
  mockProjectWebsite,
  mockProjectMobileApp,
  mockProjectSEO,
];
